import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
const member = '10000000-0000-0000-0000-000000000001';
const second = '10000000-0000-0000-0000-000000000002';
await db.exec(`create role anon; create role authenticated;
create schema auth; create table auth.users(id uuid primary key);
insert into auth.users values('${member}'),('${second}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.subject',true),'')::uuid$$;
create function current_user_role() returns text language sql stable as $$select current_setting('request.app_role',true)$$;
create function is_approved_member() returns boolean language sql stable as $$select current_user_role() in ('member','admin','owner')$$;
grant usage on schema auth to public;
create schema cron;
create table cron.job(jobid int,jobname text,active boolean);
create table cron.job_run_details(jobid int,runid int,status text,start_time timestamptz,end_time timestamptz);
insert into cron.job values(1,'dispatch-scheduled-notifications',true),(2,'test-job',true);
insert into cron.job_run_details values(1,1,'succeeded',now(),now()),(2,2,'failed',now()-interval '1 minute',now()-interval '1 minute'),(2,3,'running',now(),null);
`);
await db.exec(await fs.readFile('supabase/migrations/20260907170000_app_diagnostics.sql','utf8'));
const scalar=async(sql,params=[])=>Object.values((await db.query(sql,params)).rows[0])[0];
await db.exec("set role anon");
await assert.rejects(db.query("select report_app_diagnostic('news','fetch_failed','1.0(42)')"),/permission denied/);
await db.exec(`reset role; set role authenticated; set request.subject='${member}'; set request.app_role='frozen'`);
await assert.rejects(db.query("select report_app_diagnostic('news','fetch_failed','1.0(42)')"),/not_authorized/);
await db.exec("set request.app_role='member'");
await assert.rejects(db.query('select * from app_diagnostic_events'),/permission denied/);
await assert.rejects(db.query('select app_diagnostics_dashboard()'),/not_authorized/);
await assert.rejects(db.query("select review_app_diagnostic('news','fetch_failed','1.0(42)',now())"),/not_authorized/);
await assert.rejects(db.query("select report_app_diagnostic('phone +96512345678','fetch_failed','1.0(42)')"),/invalid_diagnostic/);
await assert.rejects(db.query("select report_app_diagnostic('news','raw error message','1.0(42)')"),/invalid_diagnostic/);
await assert.rejects(db.query("select report_app_diagnostic('news','fetch_failed','secret-token')"),/invalid_diagnostic/);
for(let i=0;i<30;i++) assert.equal(await scalar("select report_app_diagnostic('news','fetch_failed','1.0(42)')"),true);
assert.equal(await scalar("select report_app_diagnostic('media','operation_failed','1.0(42)')"),false);
await db.exec(`set request.subject='${second}'`);
assert.equal(await scalar("select report_app_diagnostic('news','fetch_failed','1.0(42)')"),true);
await db.exec("set request.app_role='admin'");
const board=await scalar('select app_diagnostics_dashboard()');
assert.equal(board.total_occurrences,31);
assert.equal(board.open_groups,1);
assert.equal(board.errors.length,1);
assert.equal(board.dispatch_healthy,true);
assert.equal(board.jobs.find(x=>x.name==='test-job').status,'failed'); // Running isn't recovery.
assert.ok(!JSON.stringify(board).includes(member));
assert.ok(!JSON.stringify(board).includes(second));
const seen=board.errors[0].last_seen;
await db.query("select review_app_diagnostic('news','fetch_failed','1.0(42)',$1)",[seen]);
assert.equal((await scalar('select app_diagnostics_dashboard()')).open_groups,0);
await db.exec('reset role');
await db.exec("update app_diagnostic_events set last_seen=last_seen+interval '1 second'");
await db.exec('set role authenticated');
assert.equal((await scalar('select app_diagnostics_dashboard()')).open_groups,1);
// A review from a stale page cannot hide a later recurrence.
await db.query("select review_app_diagnostic('news','fetch_failed','1.0(42)',$1)",[seen]);
assert.equal((await scalar('select app_diagnostics_dashboard()')).open_groups,1);
await db.exec('reset role');
await db.exec(`delete from auth.users where id='${member}'`);
assert.equal(await scalar('select count(*)::int from app_diagnostic_events'),1);
await db.exec("update app_diagnostic_events set last_seen=now()-interval '8 days'");
await db.exec('set role authenticated');
assert.equal((await scalar('select app_diagnostics_dashboard()')).errors.length,0);
console.log('PASS: diagnostics privacy, active account checks, RLS, shared hourly cap, caller binding, admin review, recurrence, stale review, cron terminal states and deletion cascade');
await db.close();
