import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
const me='10000000-0000-0000-0000-000000000001';
await db.exec(`create role anon; create role authenticated; create role service_role;
create schema auth; create schema storage;
create table auth.users(id uuid,raw_app_meta_data jsonb);
create table storage.objects(bucket_id text,name text,owner_id text);
create function auth.role() returns text language sql stable as $$select current_setting('request.role',true)$$;
create function auth.uid() returns uuid language sql stable as $$select '${me}'::uuid$$;
create function current_profile_id() returns uuid language sql stable as $$select auth.uid()$$;
create function current_user_role() returns text language sql stable as $$select 'member'::text$$;
create function is_approved_member() returns boolean language sql stable as $$select auth.role()='authenticated'$$;
grant usage on schema auth to public;
create table profiles(id uuid,status text);
create table notifications(target_member_id uuid,title text,body text,kind text,is_read bool);
create table news(id uuid primary key,created_at timestamptz not null,content text,author_name text,type text,approval_status text,author_id uuid,posted_by uuid);
create table news_likes(news_id uuid,member_id uuid);
create table news_comments(news_id uuid);
create table news_poll_votes(news_id uuid,member_id uuid,option_index int);
grant select on news,news_likes,news_comments,news_poll_votes to authenticated;
alter table news enable row level security;
create policy visible_news on news for select to authenticated using (approval_status='approved' or author_id=auth.uid());
insert into profiles values('${me}','active'),('10000000-0000-0000-0000-000000000002','frozen');
`);
for(const name of ['20260906200000_delivery_and_maintenance.sql','20260906201000_news_pagination.sql']) await db.exec(await fs.readFile('supabase/migrations/'+name,'utf8'));
async function scalar(sql,params=[]){return Object.values((await db.query(sql,params)).rows[0])[0]}
await db.exec("set request.role='authenticated'");
await assert.rejects(db.query("select reserve_delivery_attempt('test','actor','key')"),/service_only/);
await db.exec("set request.role='service_role'");
const reserve=key=>scalar("select reserve_delivery_attempt('test','actor',$1,2,300)",[key]);
assert.equal(await reserve('a'),'allowed');
assert.equal(await reserve('a'),'duplicate');
assert.equal(await reserve('b'),'allowed');
assert.equal(await reserve('c'),'rate_limited');
const concurrent=await Promise.all(Array.from({length:8},()=>scalar("select reserve_delivery_attempt('concurrent','actor','same',10,300)")));
assert.equal(concurrent.filter(x=>x==='allowed').length,1);
assert.equal((await scalar("select publish_weekly_digest('test','synthetic')")).notified,1);
assert.equal((await scalar("select publish_weekly_digest('test','synthetic')")).duplicate,true);
assert.equal(await scalar('select count(*)::int from notifications'),1);
await db.exec(`insert into storage.objects values('stories','mine.jpg','${me}'),('stories','other.jpg','10000000-0000-0000-0000-000000000002')`);
assert.equal(await scalar('select owns_story_storage_file($1,$2)',['mine.jpg',me]),true);
assert.equal(await scalar('select owns_story_storage_file($1,$2)',['other.jpg',me]),false);
console.log('PASS: service-only maintenance, durable duplicate/rate gates, weekly atomic idempotency, storage ownership');
for(let i=1;i<=57;i++) await db.query('insert into news values($1,$2,$3,$4,$5,$6,$7,null)',[
  '20000000-0000-0000-0000-'+String(i).padStart(12,'0'), '2026-09-06T12:00:00.123456Z', 'synthetic '+i, 'Author',i%2?'news':'occasion',i===57?'pending':'approved',i===57?'10000000-0000-0000-0000-000000000003':me
]);
await db.exec("set request.role='authenticated'; set role authenticated");
const page1=(await db.query('select *,created_at::text as cursor_time from news_feed_page()')).rows;
assert.equal(page1.length,25);
const cursor=page1.at(-1);
await db.exec('reset role');
// Concurrent insert and removal must not shift the cursor or duplicate older records.
await db.query("insert into news values('30000000-0000-0000-0000-000000000001','2026-09-07','new','Author','news','approved',$1,null)",[me]);
await db.query('delete from news where id=$1',[page1[0].id]);
await db.exec('set role authenticated');
const page2=(await db.query('select * from news_feed_page($1,$2)',[cursor.cursor_time,cursor.id])).rows;
assert.equal(page2.length,25);
assert.equal(new Set([...page1,...page2].map(x=>x.id)).size,50);
assert.equal((await db.query("select * from news_feed_page(null,null,'synthetic 7')")).rows.length,1);
assert.ok((await db.query("select * from news_feed_page(null,null,'','occasion',50)")).rows.every(x=>x.type==='occasion'));
assert.ok(!(await db.query('select * from news_feed_page(null,null,\'\',null,10000)')).rows.some(x=>x.approval_status==='pending'));
assert.equal((await db.query('select * from news_feed_page(null,null,\'\',null,10000)')).rows.length,50);
const stats=(await db.query('select * from news_page_stats($1)',[[page2[0].id]])).rows[0];
assert.equal(Number(stats.likes_count),0); assert.equal(Number(stats.comments_count),0); assert.equal(stats.is_liked,false);
console.log('PASS: authenticated RLS, deterministic tied timestamps, concurrent insert/delete pagination, full-feed search/type filter, bounded pages and zero counts');
await db.exec('reset role');
await db.exec('create table account_deletion_jobs(auth_user_id uuid,created_at timestamptz)');
await db.exec(await fs.readFile('supabase/migrations/20260906203000_operational_health.sql','utf8'));
await db.exec('set role authenticated');
await assert.rejects(db.query('select operational_health()'),/not_authorized/);
await db.exec('reset role');
await db.exec(`create or replace function current_user_role() returns text language sql stable as $$select 'owner'::text$$`);
assert.equal((await scalar('select operational_health()')).pending_deletions,0);
console.log('PASS: operational health rejects ordinary members and reports only aggregate counts');
await db.close();
